// Playground: https://www.figma.com/design/EFFQgT1aDH5exs2bABaIFJ/Icons?t=y0K2dHfJgpxMIl1e-0
export { default as iconGear } from './gear.svg'
export { default as iconBooks } from './books.svg'
export { default as iconSeedling } from './seedling.svg'
export { default as iconMagnifyingGlass } from './magnifying-glass.svg'
export { default as iconPencil } from './pencil.svg'
export { default as iconCompass } from './compass.svg'
export { default as iconScroll } from './scroll.svg'
export { default as iconGlobe } from './globe.svg'
export { default as iconPlug } from './plug.svg'
export { default as iconLoudspeaker } from './loudspeaker.svg'
export { default as iconCoin } from './coin.svg'
