name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          # TODO/eventually: try using the cache again
          # The cache breaks playwright installation, see https://github.com/vikejs/vike-vue/pull/119
          # cache: "pnpm"
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - run: pnpm run test
