name: CI
on: [ push, pull_request ]

jobs:
  prepare:
    # Prevent workflow being run twice, https://github.com/orgs/community/discussions/57827#discussioncomment-6579237
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          # Last time we tried pnpm 10, it crashed due to the infamous Playwright installation issue.
          # https://github.com/brillout/docpress/actions/runs/15132795104/job/42537517901
          # ```ci
          # ╔═════════════════════════════════════════════════════════════════════════╗
          # ║ Looks like Playwright Test or Playwright was just installed or updated. ║
          # ║ Please run the following command to download new browsers:              ║
          # ║                                                                         ║
          # ║     pnpm exec playwright install                                        ║
          # ║                                                                         ║
          # ║ <3 Playwright Team                                                      ║
          # ╚═════════════════════════════════════════════════════════════════════════╝
          # ```
          version: 9.1.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          # TODO/eventually: try using the cache again
          # The cache breaks playwright installation, see https://github.com/vikejs/vike-vue/pull/119
          # cache: "pnpm"
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - run: pnpm run test
